# Generated by Django 4.2.5 on 2023-10-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='whois',
            new_name='certfinder',
        ),
        migrations.AddField(
            model_name='scan',
            name='nuclei',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
