# Generated by Django 4.2.5 on 2023-10-05 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_target_whois'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(default='', max_length=1000)),
                ('domain_name', models.CharField(default='', max_length=1000)),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.target')),
            ],
        ),
    ]
