# Generated by Django 4.2.5 on 2023-10-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_target_whois_whois'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whois',
            old_name='registrar_abuse_phone',
            new_name='registrant_phone',
        ),
        migrations.RemoveField(
            model_name='whois',
            name='registrar_abuse_email',
        ),
        migrations.AddField(
            model_name='whois',
            name='registrant_fax',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
