# Generated by Django 4.2.5 on 2023-10-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_registrar_abuse_phone_whois_registrant_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whois',
            name='dnssec',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='whois',
            name='name_servers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='whois',
            name='registrant_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='whois',
            name='registrar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whois',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
