# Generated by Django 4.2.5 on 2023-10-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_whois_dnssec_alter_whois_name_servers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whois',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whois',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whois',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
