# Generated by Django 4.2.5 on 2023-10-05 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_whois_created_alter_whois_expires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whois',
            name='target',
        ),
        migrations.AddField(
            model_name='target',
            name='whois',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.whois'),
            preserve_default=False,
        ),
    ]
