# Generated by Django 4.2.5 on 2023-10-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_target_whois'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whois',
            name='domain_name',
        ),
    ]
