# Generated by Django 4.2.5 on 2023-10-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_whois_name_servers_alter_whois_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdomain',
            old_name='target_id',
            new_name='target',
        ),
    ]
