# Generated by Django 4.2.5 on 2023-10-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_scan_target_scanhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
