# Generated by Django 4.2.5 on 2023-10-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_scanhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
