# Generated by Django 4.2.5 on 2023-10-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_scan_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='ip_infos',
            field=models.JSONField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='domain_name',
            field=models.CharField(default='', max_length=1000, unique=True),
        ),
    ]
