# Generated by Django 4.2.5 on 2023-10-07 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_target_ip_infos_alter_subdomain_domain_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_continent', models.CharField(max_length=100)),
                ('location_country', models.CharField(max_length=100)),
                ('location_country_code', models.CharField(max_length=2)),
                ('location_postal_code', models.CharField(blank=True, max_length=20)),
                ('location_timezone', models.CharField(max_length=100)),
                ('location_latitude', models.FloatField()),
                ('location_longitude', models.FloatField()),
                ('location_registered_country', models.CharField(max_length=100)),
                ('location_registered_country_code', models.CharField(max_length=2)),
                ('location_updated_at', models.DateTimeField()),
                ('last_updated_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='target',
            name='ip_infos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ipinfos'),
        ),
    ]
