# Generated by Django 4.2.5 on 2023-10-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_target_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='ip',
        ),
        migrations.AddField(
            model_name='target',
            name='domain_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
