# Generated by Django 4.2.5 on 2023-10-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_ipinfos_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='source',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
