# Generated by Django 4.2.5 on 2023-10-08 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_subdomain_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='found_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
