# Generated by Django 4.2.5 on 2023-10-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_subdomain_found_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='ip_infos',
        ),
        migrations.RemoveField(
            model_name='target',
            name='whois',
        ),
        migrations.AddField(
            model_name='ipinfos',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_infos', to='home.target'),
        ),
        migrations.AddField(
            model_name='whois',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whois_infos', to='home.target'),
        ),
    ]
