# Generated by Django 4.2.5 on 2023-10-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_target_ip_infos_remove_target_whois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='command',
            field=models.CharField(default='ee', max_length=1000),
            preserve_default=False,
        ),
    ]
