# Generated by Django 4.2.5 on 2023-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_scanhistory_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='ip_iso',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
