# Generated by Django 4.2.5 on 2023-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_subdomain_ip_iso'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='is_interesting',
            field=models.BooleanField(default=False),
        ),
    ]
